[[rulesets]]
group = "ğŸŒ± Home"
ruleset = "https://darin-public.s3.bitiful.net/subConfig/subConfigs/Rules/Home.list"

[[rulesets]]
group = "âœˆï¸ Proxy"
ruleset = "https://darin-public.s3.bitiful.net/subConfig/subConfigs/Rules/Proxy.list"

[[rulesets]]
group = "âœˆï¸ Download"
ruleset = "https://darin-public.s3.bitiful.net/subConfig/subConfigs/Rules/Download.list"

[[rulesets]]
group = "âœˆï¸ Github"
ruleset = "https://darin-public.s3.bitiful.net/subConfig/subConfigs/Rules/Github.list"

[[rulesets]]
group = "âœˆï¸ OpenAi"
ruleset = "https://darin-public.s3.bitiful.net/subConfig/subConfigs/Rules/OpenAi.list"

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "https://darin-public.s3.bitiful.net/subConfig/subConfigs/Rules/Direct.list"