[[rulesets]]
group = "ğŸŒ± Home"
ruleset = "https://raw.githubusercontent.com/Darin726/subConfigs/refs/heads/main/Rules/Home.list"

[[rulesets]]
group = "âœˆï¸ Proxy"
ruleset = "https://raw.githubusercontent.com/Darin726/subConfigs/refs/heads/main/Rules/Proxy.list"

[[rulesets]]
group = "âœˆï¸ Download"
ruleset = "https://raw.githubusercontent.com/Darin726/subConfigs/refs/heads/main/Rules/Download.list"

[[rulesets]]
group = "âœˆï¸ Github"
ruleset = "https://raw.githubusercontent.com/Darin726/subConfigs/refs/heads/main/Rules/Github.list"

[[rulesets]]
group = "âœˆï¸ OpenAi"
ruleset = "https://raw.githubusercontent.com/Darin726/subConfigs/refs/heads/main/Rules/OpenAi.list"

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "https://raw.githubusercontent.com/Darin726/subConfigs/refs/heads/main/Rules/Direct.list"