[[rulesets]]
group = "ğŸŒ± Home"
ruleset = "qianlicao/rules/Home.list"

[[rulesets]]
group = "âœˆï¸ Proxy"
ruleset = "qianlicao/rules/Proxy.list"

[[rulesets]]
group = "âœˆï¸ Download"
ruleset = "qianlicao/rules/Download.list"

[[rulesets]]
group = "âœˆï¸ Github"
ruleset = "qianlicao/rules/Github.list"

[[rulesets]]
group = "âœˆï¸ OpenAi"
ruleset = "qianlicao/rules/OpenAi.list"

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "qianlicao/rules/Direct.list"