[[custom_groups]]
name = "ğŸ”° èŠ‚ç‚¹é€‰æ‹©"
type = "select"
rule = ["[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©", "[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©_HK", "[]ğŸ¯ å…¨çƒç›´è¿", "[]ğŸ‡­ğŸ‡° HK", ".*"]

[[custom_groups]]
name = "â™»ï¸ è‡ªåŠ¨é€‰æ‹©"
type = "url-test"
rule = [".*"]
url = "http://www.gstatic.com/generate_204"
interval = 300

[[custom_groups]]
name = "â™»ï¸ è‡ªåŠ¨é€‰æ‹©_HK"
type = "url-test"
rule = ["(HGC|HKBN|HKT|æ·±å°|å½°åŒ–|æ—¥æœ¬|ä¸œäº¬|é¦–å°”|hk|Hong|HK|SG|TW|JP|Japan|æ¸¯|tw)"]
url = "http://www.gstatic.com/generate_204"
interval = 300

[[custom_groups]]
name = "ğŸ‡­ğŸ‡° HK"
type = "select"
rule = ["(HGC|HKBN|HKT|æ·±å°|å½°åŒ–|æ—¥æœ¬|ä¸œäº¬|é¦–å°”|hk|Hong|HK|SG|TW|JP|Japan|æ¸¯|tw)"]

[[custom_groups]]
name = "ğŸŒ± Home"
type = "select"
rule = ["[]ğŸ¯ å…¨çƒç›´è¿",
"(Ubuntu)",
"[]ğŸ”° èŠ‚ç‚¹é€‰æ‹©"]

[[custom_groups]]
name = "âœˆï¸ Proxy"
type = "select"
rule = [
    "[]ğŸ”° èŠ‚ç‚¹é€‰æ‹©",
    "[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©",
    "[]ğŸ¯ å…¨çƒç›´è¿",
    ".*"
]

[[custom_groups]]
name = "âœˆï¸ Download"
type = "select"
rule = [
    "[]ğŸ”° èŠ‚ç‚¹é€‰æ‹©",
    "[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©",
    "[]ğŸ¯ å…¨çƒç›´è¿",
    ".*"
]

[[custom_groups]]
name = "âœˆï¸ OpenAi"
type = "select"
rule = [
    "[]ğŸ”° èŠ‚ç‚¹é€‰æ‹©",
    "[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©",
    "[]ğŸ¯ å…¨çƒç›´è¿",
    ".*"
]

[[custom_groups]]
name = "âœˆï¸ Github"
type = "select"
rule = [
    "[]ğŸ”° èŠ‚ç‚¹é€‰æ‹©",
    "[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©",
    "[]ğŸ¯ å…¨çƒç›´è¿",
    ".*"
]

